---
title: "TidyTuesday 2023/01 - Workouts data"
author: "Johan S. Sáenz"
date: "2023-01-06"
output:
  html_document:
  theme: paper
highlight: kate
editor: source
knitr:
  opts_chunk:
    dev: "ragg_png"
    retina: 2
    dpi: 600
execute:
  freeze: auto
  echo: true
  fig-width: 5
  fig-height: 6
---

```{r}
#| label: prep
#| message: false
#| warning: false
library(XML)
library(tidyverse)
library(lubridate)
library(patchwork)
library(ggtext)
library(showtext)
library(here)
```

## Data

```{r}
#| label: data
#| message: false
#| warning: false
health_xml <- xmlParse(here::here("rawdata/apple_health_export_2025/export.xml"))

health_df <- XML:::xmlAttrsToDataFrame(health_xml["//Record"], 
                                       stringsAsFactors = FALSE) %>%
  as_tibble() %>% mutate(value = as.numeric(value))

activity_df <- XML:::xmlAttrsToDataFrame(health_xml["//ActivitySummary"], 
                                         stringsAsFactors = FALSE) %>% 
  as_tibble()

workout_df <-  XML:::xmlAttrsToDataFrame(health_xml["//Workout"], 
                                         stringsAsFactors = FALSE) %>% 
  as_tibble() %>% 
  mutate(duration=as.numeric(duration))
```

## Wrangling data

```{r}
#| label: wrangling
#| message: false
#| warning: false
calories <- activity_df %>% 
  dplyr::mutate(dateComponents = lubridate::date(dateComponents),
                year = lubridate::year(dateComponents), 
                month = lubridate::month(dateComponents, label = TRUE), 
                day = lubridate::day(dateComponents),
                week = lubridate::week(ymd(dateComponents)),
                activeEnergyBurned = as.numeric(activeEnergyBurned),
                activeEnergyBurnedGoal = as.numeric(activeEnergyBurnedGoal)) %>% 
  dplyr::mutate(calories_goal = activeEnergyBurned >=activeEnergyBurnedGoal,
                exercise_goal =appleExerciseTime >=appleExerciseTimeGoal,
                stand_goal = appleStandHours >= appleStandHoursGoal) %>% 
  dplyr::filter(year==2025)

wk_type <- workout_df %>% 
  mutate(creationDate = str_remove(creationDate, " .*"),
         workoutActivityType= str_replace(workoutActivityType, "HKWorkoutActivityType", "")) %>% 
  dplyr::mutate(year = lubridate::year(creationDate), 
                month = lubridate::month(creationDate, label = TRUE), 
                day = lubridate::day(creationDate),
                week = lubridate::week(ymd(creationDate))) %>% 
  dplyr::filter(year==2025) %>% 
  full_join(activity_df, by=c("creationDate"="dateComponents")) %>% 
  dplyr::filter(year==2025) 

weight <- health_df %>%
  filter(type=="HKQuantityTypeIdentifierBodyMass") %>% 
  mutate(creationDate = str_remove(creationDate, " .*")) %>% 
  dplyr::mutate(year = lubridate::year(creationDate), 
                month = lubridate::month(creationDate, label = TRUE), 
                day = lubridate::day(creationDate),
                week = lubridate::week(ymd(creationDate))) %>% 
  filter(year == 2025) %>% 
  full_join(activity_df, by=c("creationDate"="dateComponents")) %>% 
  filter(year == 2025) 
  
  
```

## Plots

```{r}
#| label: plotting
#| message: false
#| warning: false

calories_arrows <-
  tibble(
    x1 = as.Date("2025-03-20"),
    x2 = as.Date("2025-03-06"),
    y1 = 1250,
    y2 = 1160
  )

calories_plot <- calories %>% 
  ggplot(aes(x = dateComponents,
             y = activeEnergyBurned )) +
  geom_col(aes(fill=calories_goal))  +
  scale_y_continuous(limits = c(0, 2100),
                     expand = c(0,0)) +
  scale_x_date(date_breaks ="1 month",
               date_minor_breaks = "1 week",
               date_labels = "%B",
               limits = c(as.Date("2025-01-01"), as.Date("2025-12-31")),
               expand = c(0, 0)
               ) +
  scale_fill_manual(values = c("#7a04eb", "#1afe49")) +
  labs(x = NULL,
       y = "Active calories") +
 # facet_grid(rows = vars(month)) +
  theme_classic() +
  theme(strip.text.y = element_text(angle = 0),
        legend.position = "none",
        legend.title = element_blank(),
        plot.background = element_rect(colour = "black",
                                       fill = "black"),
        panel.background = element_rect(colour = "black",
                                        fill = "black"),
        legend.background = element_rect(colour = "black",
                                         fill = "black"),
        axis.title = element_text(colour = "white",
                                  face = "bold"),
        axis.text = element_text(colour = "white"),
        axis.text.x = element_blank(),
        plot.margin = unit(c(1,1,1,1), units = "cm")) +
  annotate(
    "text", x = as.Date("2025-03-21"), y = 1350, size = 3.5, color = "lightgray",
    face = "bold",
    lineheight = .9, label = glue::glue("Goal achived")
    ) +
  geom_curve(data = calories_arrows, aes(x = x1, y = y1, xend = x2, yend = y2),
    arrow = arrow(length = unit(0.07, "inch")), size = 0.4,
    color = "grey", curvature = -0.3)

wk_arrows <-
  tibble(
    x1 = as.Date("2025-08-15"),
    x2 = as.Date("2025-09-07"),
    y1 = 100,
    y2 = 52
  )

wk_plot <- wk_type %>% 
  ggplot(aes(x=date(creationDate),
             y=duration)) +
  geom_point(aes(color=workoutActivityType), 
             size=1,
             alpha=0.7) +
  scale_x_date(date_breaks = "1 month", 
               date_minor_breaks = "1 week",
               date_labels = "%B",
               limits = c(as.Date("2025-01-01"), as.Date("2025-12-31")),
               expand = c(0,0)) +
  scale_color_manual(values = c("#e96d5e", "#ff9760", "#ffe69d", "#6a7e6a",
                                "#7700a6", "#defe47", "#00b3fe", "#ff184c",
                                "grey", "orange", "blue","darkgreen")) +
  labs(x = NULL,
       y = "Time (min)") +
  theme_classic() +
  guides(color = guide_legend(override.aes = list(size = 2),
                              nrow = 2)) +
  theme(legend.position = "top",
        legend.title = element_blank(),
        legend.text = element_text(colour = "white"),
        plot.background = element_rect(colour = "black",
                                       fill = "black"),
        panel.background = element_rect(colour = "black",
                                        fill = "black"),
        legend.background = element_rect(colour = "black",
                                         fill = "black"),
        axis.title = element_text(colour = "white",
                                  face = "bold"),
        axis.text = element_text(colour = "white"),
        axis.text.x = element_blank()) +
  annotate(
    "text", x = as.Date("2025-08-05"), y = 100, size = 3.5, color = "lightgray",
    face = "bold",
    lineheight = .9, label = glue::glue("Workout")
    ) +
  geom_curve(data = wk_arrows, aes(x = x1, y = y1, xend = x2, yend = y2),
    arrow = arrow(length = unit(0.07, "inch")), size = 0.4,
    color = "grey", curvature = -0.3)

weight_plot <- weight %>% 
  ggplot(aes(x = date(creationDate),
             y = value)) +
  geom_line(color = "#defe47") +
  #geom_hline(yintercept = 90, color = "darkgrey", linetype = "dashed") +
  scale_y_continuous(limits = c(85, 105)) +
  scale_x_date(date_breaks = "1 month",
               date_labels = "%B",
               limits = c(as.Date("2025-01-01"), as.Date("2025-12-31")),
               expand = c(0,0)) +
  labs(x = NULL,
       y = "Weight") +
  theme_classic() +
  theme(plot.background = element_rect(colour = "black",
                                       fill = "black"),
        panel.background = element_rect(colour = "black",
                                        fill = "black"),
        axis.title = element_text(colour = "white",
                                  face = "bold"),
        axis.text = element_text(colour = "white"),
        axis.text.x = element_text(size = 12),
        axis.text.y = element_blank())

plot_all <-  (wk_plot / calories_plot  / weight_plot)



final_plot <- plot_all + 
  plot_annotation(title = "A YEAR OF DATA (2025)",
                  subtitle = "I tracked my workouts, weight and active calories using
                  a smartwatch during 2025. One of my goals was to <b style='color:#1afe49'>burn 850 active calories</b> 
                  per day.",
                  caption = "Visualization by Johan S. Sáenz (@SaenzJohanS) • Data collected with AppleWatch") & 
  theme(plot.background = element_rect(fill = "black"),
        plot.title = element_markdown(family = "American Typewriter",
                                      colour = "white",
                                      face = "bold",
                                      size = 30,
                                      margin = margin(10, 10, 10, 10)),
        plot.subtitle = element_markdown(color = "white",
                                         lineheight = 1,),
        plot.caption = element_markdown(color = "white", 
                                        size = 7,
                                        hjust = 0.5))
```

## Saving plots

```{r}
ggsave(final_plot,
       file = here::here("plot/workouts_2025.png"), 
       width = 12, height = 7, dpi = 400)
```
